<?php

namespace Database\Seeders;

use App\Models\Report\ReportCityRatio;
use App\Models\Report\ReportDistrictRatio;
use App\Models\Report\ReportRatio;
use App\Repositories\Enums\Reports\Prt\IPrtReport;
use App\Repositories\Enums\Reports\Ser\IBusinessStatisticsRatioEnum;
use App\Repositories\Enums\Reports\Ser\IIndustryRatioReport;
use App\Repositories\Enums\Reports\Ser\IInvestmentReport;
use App\Repositories\Enums\Reports\Ser\ITradeRatioReport;
use Illuminate\Database\Seeder;

class SerPrtRatiosOrderAndGroupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    final public function run(): void
    {
        $ratios = [
            // IBusinessStatisticsRatioEnum
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumber,
                'order' => 1.,
                'group' => trans('report.ratios.group.common'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumber,
                'order' => 2.,
                'group' => trans('report.ratios.group.common'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryForestAndFishing,
                'order' => 4,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryForestAndFishing'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryMining,
                'order' => 5,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryMining'),

            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryManufacture,
                'order' => 6,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryManufacture'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustrySupply,
                'order' => 7,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustrySupply'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryWaste,
                'order' => 8,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryWaste'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryBuild,
                'order' => 9,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryBuild'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryTradeAndRepair,
                'order' => 10,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryTradeAndRepair'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryLogistic,
                'order' => 11,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryLogistic'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryAccommodationAndFood,
                'order' => 12,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryAccommodationAndFood'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryInformAndCommunication,
                'order' => 13,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryInformAndCommunication'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryFinanceAndInsurance,
                'order' => 14,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryFinanceAndInsurance'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryRealEstate,
                'order' => 15,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryRealEstate'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryScience,
                'order' => 16,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryScience'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryAdministrateAndSupport,
                'order' => 17,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryAdministrateAndSupport'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryGovernmentAndDefence,
                'order' => 18,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryGovernmentAndDefence'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryEducation,
                'order' => 19,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryEducation'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryHealthCare,
                'order' => 20,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryHealthCare'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryArtsAndEntertainment,
                'order' => 21,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryArtsAndEntertainment'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryOther,
                'order' => 22,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryOther'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryHouseHold,
                'order' => 23,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryHouseHold'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberIndustryExtraterritorial,
                'order' => 24,
                'group' => trans('report.ratios.group.business-stat.registered-industry'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberIndustryExtraterritorial'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberDistrict,
                'order' => 25,
                'group' => trans('report.ratios.group.common'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberBySizeSmall,
                'order' => 26,
                'group' => trans('report.ratios.group.business-stat.registered-sizes'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberBySizeSmall'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberBySizeMedium,
                'order' => 27,
                'group' => trans('report.ratios.group.business-stat.registered-sizes'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberBySizeMedium'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::RegisteredEnterprisesNumberBySizeLarge,
                'order' => 28,
                'group' => trans('report.ratios.group.business-stat.registered-sizes'),
                'name'  => trans('report.BusinessStat.RegisteredEnterprisesNumberBySizeLarge'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberDistrict,
                'order' => 29,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberDistrict'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryForestAndFishing,
                'order' => 30,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryForestAndFishing'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryMining,
                'order' => 31,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryMining'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryManufacture,
                'order' => 32,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryManufacture'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustrySupply,
                'order' => 33,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustrySupply'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryWaste,
                'order' => 34,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryWaste'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryBuild,
                'order' => 35,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryBuild'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryTradeAndRepair,
                'order' => 36,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryTradeAndRepair'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryLogistic,
                'order' => 37,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryLogistic'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryAccommodationAndFood,
                'order' => 38,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryAccommodationAndFood'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryInformAndCommunication,
                'order' => 39,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryInformAndCommunication'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryFinanceAndInsurance,
                'order' => 40,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryFinanceAndInsurance'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryRealEstate,
                'order' => 41,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryRealEstate'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryScience,
                'order' => 42,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryScience'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryAdministrateAndSupport,
                'order' => 43,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryAdministrateAndSupport'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryGovernmentAndDefence,
                'order' => 44,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryGovernmentAndDefence'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryEducation,
                'order' => 45,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryEducation'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryHealthCare,
                'order' => 46,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryHealthCare'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryArtsAndEntertainment,
                'order' => 47,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryArtsAndEntertainment'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryOther,
                'order' => 48,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryOther'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryHouseHold,
                'order' => 49,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryHouseHold'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberIndustryExtraterritorial,
                'order' => 50,
                'group' => trans('report.ratios.group.business-stat.operating-industry'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberIndustryExtraterritorial'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberBySizeSmall,
                'order' => 54,
                'group' => trans('report.ratios.group.business-stat.operating-sizes'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberBySizeSmall'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberBySizeMedium,
                'order' => 52,
                'group' => trans('report.ratios.group.business-stat.operating-sizes'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberBySizeMedium'),
            ],
            [
                'id'    => IBusinessStatisticsRatioEnum::OperatingEnterprisesNumberBySizeLarge,
                'order' => 53,
                'group' => trans('report.ratios.group.business-stat.operating-sizes'),
                'name'  => trans('report.BusinessStat.OperatingEnterprisesNumberBySizeLarge'),
            ],
            // IIndustryRatioReport
            [
                'id'    => IIndustryRatioReport::EnterpriseNumber,
                'order' => 1,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Industry.fields.EnterpriseNumber'),
            ],
            [
                'id'    => IIndustryRatioReport::Employed,
                'order' => 2,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Industry.fields.Employed'),
            ],
            [
                'id'    => IIndustryRatioReport::AverageSalary,
                'order' => 3,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Industry.fields.AverageSalary'),
            ],
            [
                'id'    => IIndustryRatioReport::TaxRevenues,
                'order' => 3,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Industry.fields.TaxRevenues'),
            ],
            [
                'id'    => IIndustryRatioReport::IndustrialProductionVolume,
                'order' => 4,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Industry.fields.IndustrialProductionVolume'),
            ],
            [
                'id'    => IIndustryRatioReport::IndustrialProductionVolumeIndustryMining,
                'order' => 5,
                'group' => trans('report.ratios.group.industry.ifo'),
                'name'  => trans('report.Industry.fields.IndustrialProductionVolumeIndustryMining'),
            ],
            [
                'id'    => IIndustryRatioReport::IndustrialProductionVolumeIndustryManufacturing,
                'order' => 6,
                'group' => trans('report.ratios.group.industry.ifo'),
                'name'  => trans('report.Industry.fields.IndustrialProductionVolumeIndustryManufacturing'),
            ],
            [
                'id'    => IIndustryRatioReport::IndustrialProductionVolumeIndustrySupply,
                'order' => 7,
                'group' => trans('report.ratios.group.industry.ifo'),
                'name'  => trans('report.Industry.fields.IndustrialProductionVolumeIndustrySupply'),
            ],
            [
                'id'    => IIndustryRatioReport::IndustrialProductionVolumeIndustryWaterAndWaste,
                'order' => 8,
                'group' => trans('report.ratios.group.industry.ifo'),
                'name'  => trans('report.Industry.fields.IndustrialProductionVolumeIndustryWaterAndWaste'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryOutput,
                'order' => 9,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryOutput'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureEngineering,
                'order' => 10,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureEngineering'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureLight,
                'order' => 11,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureLight'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureFood,
                'order' => 12,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureDrink'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureDrink,
                'order' => 13,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureDrink'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureTobacco,
                'order' => 14,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureTobacco'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureWoodAndCork,
                'order' => 15,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureWoodAndCork'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructurePaper,
                'order' => 16,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructurePaper'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructurePrintingAndMedia,
                'order' => 17,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructurePrintingAndMedia'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructurePetroleum,
                'order' => 18,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructurePetroleum'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureChemical,
                'order' => 19,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureChemical'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructurePharmaceutical,
                'order' => 20,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructurePharmaceutical'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureRubberAndPlastic,
                'order' => 21,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureRubberAndPlastic'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureOtherNonMetal,
                'order' => 22,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureOtherNonMetal'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureMetallurgical,
                'order' => 23,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureMetallurgical'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureMetalProductsNonMachinery,
                'order' => 24,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureMetalProductsNonMachinery'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureFurniture,
                'order' => 25,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureFurniture'),
            ],
            [
                'id'    => IIndustryRatioReport::ManufacturingIndustryStructureOther,
                'order' => 26,
                'group' => trans('report.ratios.group.industry.structure'),
                'name'  => trans('report.Industry.fields.ManufacturingIndustryStructureOther'),
            ],
            [
                'id'    => IIndustryRatioReport::PhysicalVolumeIndexIndustrialProduction,
                'order' => 27,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Industry.fields.PhysicalVolumeIndexIndustrialProduction'),
            ],
            [
                'id'    => IIndustryRatioReport::PhysicalVolumeIndexManufacturing,
                'order' => 28,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Industry.fields.PhysicalVolumeIndexManufacturing'),
            ],
            // IInvestmentReport
            [
                'id'    => IInvestmentReport::InvestmentSize,
                'order' => 1,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Investments.fields.InvestmentSize'),
            ],
            [
                'id'    => IInvestmentReport::PhysicalVolumeIndex,
                'order' => 2,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Investments.fields.PhysicalVolumeIndex'),
            ],
            [
                'id'    => IInvestmentReport::InternalInvestment,
                'order' => 3,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Investments.fields.InternalInvestment'),
            ],
            [
                'id'    => IInvestmentReport::ExternalInvestment,
                'order' => 4,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Investments.fields.ExternalInvestment'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityForestAndFishing,
                'order' => 5,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityForestAndFishing'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityIndustry,
                'order' => 6,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityIndustry'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityBuild,
                'order' => 7,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityBuild'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityTradeAndRepair,
                'order' => 8,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityTradeAndRepair'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityLogistic,
                'order' => 9,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityLogistic'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityAccommodationAndFood,
                'order' => 10,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityAccommodationAndFood'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityInformAndCommunication,
                'order' => 11,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityInformAndCommunication'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityFinanceAndInsurance,
                'order' => 12,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityFinanceAndInsurance'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityRealEstate,
                'order' => 13,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityRealEstate'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityScience,
                'order' => 14,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityScience'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityAdministrateAndSupport,
                'order' => 15,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityAdministrateAndSupport'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityGovernmentAndDefence,
                'order' => 16,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityGovernmentAndDefence'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityEducation,
                'order' => 17,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityEducation'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityHealthCare,
                'order' => 18,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityHealthCare'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityArtsAndEntertainment,
                'order' => 19,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityArtsAndEntertainment'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentVolumeByActivityOther,
                'order' => 20,
                'group' => trans('report.ratios.group.invest.activity'),
                'name'  => trans('report.Investments.fields.InvestmentVolumeByActivityOther'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentByDistrict,
                'order' => 21,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Investments.fields.InvestmentByDistrict'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentBySizeOfEnterprisesSmall,
                'order' => 22,
                'group' => trans('report.ratios.group.invest.size'),
                'name'  => trans('report.Investments.fields.InvestmentBySizeOfEnterprisesSmall'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentBySizeOfEnterprisesMedium,
                'order' => 23,
                'group' => trans('report.ratios.group.invest.size'),
                'name'  => trans('report.Investments.fields.InvestmentBySizeOfEnterprisesMedium'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentBySizeOfEnterprisesLarge,
                'order' => 24,
                'group' => trans('report.ratios.group.invest.size'),
                'name'  => trans('report.Investments.fields.InvestmentBySizeOfEnterprisesLarge'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentByCostTypeBuilding,
                'order' => 25,
                'group' => trans('report.ratios.group.invest.cost'),
                'name'  => trans('report.Investments.fields.InvestmentByCostTypeBuilding'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentByCostTypeFarm,
                'order' => 26,
                'group' => trans('report.ratios.group.invest.cost'),
                'name'  => trans('report.Investments.fields.InvestmentByCostTypeFarm'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentByCostTypeStockRaising,
                'order' => 27,
                'group' => trans('report.ratios.group.invest.cost'),
                'name'  => trans('report.Investments.fields.InvestmentByCostTypeStockRaising'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentByCostTypeOtherCapital,
                'order' => 28,
                'group' => trans('report.ratios.group.invest.cost'),
                'name'  => trans('report.Investments.fields.InvestmentByCostTypeOtherCapital'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentByCostTypeMachinery,
                'order' => 29,
                'group' => trans('report.ratios.group.invest.cost'),
                'name'  => trans('report.Investments.fields.InvestmentByCostTypeMachinery'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentByCostTypeIt,
                'order' => 30,
                'group' => trans('report.ratios.group.invest.cost'),
                'name'  => trans('report.Investments.fields.InvestmentByCostTypeIt'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentByCostTypeExploration,
                'order' => 31,
                'group' => trans('report.ratios.group.invest.cost'),
                'name'  => trans('report.Investments.fields.InvestmentByCostTypeExploration'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentByCostTypeOther,
                'order' => 32,
                'group' => trans('report.ratios.group.invest.cost'),
                'name'  => trans('report.Investments.fields.InvestmentByCostTypeOther'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentIfoDynamic,
                'order' => 33,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Investments.fields.InvestmentIfoDynamic'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentGovernmentRepublic,
                'order' => 34,
                'group' => trans('report.ratios.group.invest.government'),
                'name'  => trans('report.Investments.fields.InvestmentGovernmentRepublic'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentOwn,
                'order' => 35,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Investments.fields.InvestmentOwn'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentGovernmentLocal,
                'order' => 36,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Investments.fields.InvestmentGovernmentLocal'),
            ],
            [
                'id'    => IInvestmentReport::InvestmentLoan,
                'order' => 37,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Investments.fields.InvestmentLoan'),
            ],
            // ITradeRatioReport
            [
                'id'    => ITradeRatioReport::EnterpriseNumber,
                'order' => 1,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.EnterpriseNumber'),
            ],
            [
                'id'    => ITradeRatioReport::Employed,
                'order' => 2,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.Employed'),
            ],
            [
                'id'    => ITradeRatioReport::AverageSalary,
                'order' => 3,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.AverageSalary'),
            ],
            [
                'id'    => ITradeRatioReport::TaxRevenues,
                'order' => 4,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.TaxRevenues'),
            ],
            [
                'id'    => ITradeRatioReport::TradeWholesaleTurnover,
                'order' => 5,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.TradeWholesaleTurnover'),
            ],
            [
                'id'    => ITradeRatioReport::TradeWholesaleStructureFood,
                'order' => 6,
                'group' => trans('report.ratios.group.trade.wholesale-turnover'),
                'name'  => trans('report.Trade.fields.TradeWholesaleStructureFood'),
            ],
            [
                'id'    => ITradeRatioReport::TradeWholesaleStructureNonFood,
                'order' => 7,
                'group' => trans('report.ratios.group.trade.wholesale-turnover'),
                'name'  => trans('report.Trade.fields.TradeWholesaleStructureNonFood'),
            ],
            [
                'id'    => ITradeRatioReport::TradeWholesalePhysicalVolumeIndex,
                'order' => 8,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.TradeWholesalePhysicalVolumeIndex'),
            ],
            [
                'id'    => ITradeRatioReport::TradeWholesaleTurnoverByYears,
                'order' => 9,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.TradeWholesaleTurnoverByYears'),
            ],
            [
                'id'    => ITradeRatioReport::TradeWholesaleTurnoverByDistrict,
                'order' => 10,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.TradeWholesaleTurnoverByDistrict'),
            ],
            [
                'id'    => ITradeRatioReport::TradeRetailTurnover,
                'order' => 11,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.TradeRetailTurnover'),
            ],
            [
                'id'    => ITradeRatioReport::TradeRetailStructureFood,
                'order' => 12,
                'group' => trans('report.ratios.group.trade.retail-structure'),
                'name'  => trans('report.Trade.fields.TradeRetailStructureFood'),
            ],
            [
                'id'    => ITradeRatioReport::TradeRetailStructureNonFood,
                'order' => 13,
                'group' => trans('report.ratios.group.trade.retail-structure'),
                'name'  => trans('report.Trade.fields.TradeRetailStructureNonFood'),
            ],
            [
                'id'    => ITradeRatioReport::TradeRetailPhysicalVolumeIndex,
                'order' => 14,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.TradeRetailPhysicalVolumeIndex'),
            ],
            [
                'id'    => ITradeRatioReport::TradeRetailTurnoverByYears,
                'order' => 15,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.TradeRetailTurnoverByYears'),
            ],
            [
                'id'    => ITradeRatioReport::TradeRetailTurnoverByDistrict,
                'order' => 16,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.Trade.fields.TradeRetailTurnoverByDistrict'),
            ],
            // IPrtReport
            [
                'id'    => IPrtReport::PhysicalVolumeIndexProcessingIndustrialPlan,
                'order' => 1,
                'group' => trans('report.ratios.group.prt.ifo-processing-industry'),
                'name'  => trans('report.PRT.fields.PhysicalVolumeIndexProcessingIndustrialPlan'),
            ],
            [
                'id'    => IPrtReport::PhysicalVolumeIndexProcessingIndustrialFact,
                'order' => 2,
                'group' => trans('report.ratios.group.prt.ifo-processing-industry'),
                'name'  => trans('report.PRT.fields.PhysicalVolumeIndexProcessingIndustrialFact'),
            ],
            [
                'id'    => IPrtReport::NonResourceExportGrowthPlan,
                'order' => 3,
                'group' => trans('report.ratios.group.prt.non-resource-export-growth'),
                'name'  => trans('report.PRT.fields.NonResourceExportGrowthPlan'),
            ],
            [
                'id'    => IPrtReport::NonResourceExportGrowthFact,
                'order' => 4,
                'group' => trans('report.ratios.group.prt.non-resource-export-growth'),
                'name'  => trans('report.PRT.fields.NonResourceExportGrowthFact'),
            ],
            [
                'id'    => IPrtReport::NonResourceExportGrowthFact,
                'order' => 5,
                'group' => trans('report.ratios.group.prt.non-resource-export-growth'),
                'name'  => trans('report.PRT.fields.NonResourceExportGrowthFact'),
            ],
            [
                'id'    => IPrtReport::MainCapitalInvestmentsPlan,
                'order' => 6,
                'group' => trans('report.ratios.group.prt.invest-main-capital'),
                'name'  => trans('report.PRT.fields.MainCapitalInvestmentsPlan'),
            ],
            [
                'id'    => IPrtReport::MainCapitalInvestmentsPlanAmount,
                'order' => 7,
                'group' => trans('report.ratios.group.prt.invest-main-capital'),
                'name'  => trans('report.PRT.fields.MainCapitalInvestmentsPlanAmount'),
            ],
            [
                'id'    => IPrtReport::MainCapitalInvestmentsFact,
                'order' => 8,
                'group' => trans('report.ratios.group.prt.invest-main-capital'),
                'name'  => trans('report.PRT.fields.MainCapitalInvestmentsFact'),
            ],
            [
                'id'    => IPrtReport::IfoProcessingIndustrialDynamic,
                'order' => 9,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.PRT.fields.IfoProcessingIndustrialDynamic'),
            ],
            [
                'id'    => IPrtReport::NonResourceExportDynamic,
                'order' => 10,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.PRT.fields.NonResourceExportDynamic'),
            ],
            [
                'id'    => IPrtReport::MainCapitalInvestmentsInvestmentsDynamic,
                'order' => 11,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.PRT.fields.MainCapitalInvestmentsInvestmentsDynamic'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryIfoUp,
                'order' => 12,
                'group' => trans('report.ratios.group.common'),
                'name'  => trans('report.PRT.fields.Top5IndustryIfoUp'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryIndustrial,
                'order' => 13,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryIndustrial'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryForestAndFishing,
                'order' => 14,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryForestAndFishing'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryBuild,
                'order' => 15,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryBuild'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryTradeAndRepair,
                'order' => 16,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryTradeAndRepair'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryLogistic,
                'order' => 17,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryLogistic'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryAccommodationAndFood,
                'order' => 18,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryAccommodationAndFood'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryInformAndCommunication,
                'order' => 19,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryInformAndCommunication'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryFinanceAndInsurance,
                'order' => 20,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryFinanceAndInsurance'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryRealEstate,
                'order' => 21,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryRealEstate'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryScience,
                'order' => 22,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryScience'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryAdministrateAndSupport,
                'order' => 23,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryAdministrateAndSupport'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryGovernmentAndDefence,
                'order' => 24,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryGovernmentAndDefence'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryEducation,
                'order' => 25,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryEducation'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryHealthCare,
                'order' => 26,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryHealthCare'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryArtsAndEntertainment,
                'order' => 27,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryArtsAndEntertainment'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryOther,
                'order' => 28,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryOther'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryHouseHold,
                'order' => 29,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryHouseHold'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryExtraterritorial,
                'order' => 30,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryExtraterritorial'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryMining,
                'order' => 31,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryMining'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryManufacture,
                'order' => 32,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryManufacture'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustrySupply,
                'order' => 33,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustrySupply'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoIndustryWaste,
                'order' => 34,
                'group' => trans('report.ratios.group.prt.ifo-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoIndustryWaste'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportIndustrial,
                'order' => 35,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportIndustrial'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportForestAndFishing,
                'order' => 36,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportForestAndFishing'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportBuild,
                'order' => 37,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportBuild'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportTradeAndRepair,
                'order' => 38,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportTradeAndRepair'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportLogistic,
                'order' => 39,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportLogistic'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportAccommodationAndFood,
                'order' => 40,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportAccommodationAndFood'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportInformAndCommunication,
                'order' => 41,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportInformAndCommunication'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportFinanceAndInsurance,
                'order' => 42,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportFinanceAndInsurance'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportRealEstate,
                'order' => 43,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportRealEstate'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportScience,
                'order' => 44,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportScience'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportAdministrateAndSupport,
                'order' => 45,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportAdministrateAndSupport'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportGovernmentAndDefence,
                'order' => 46,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportGovernmentAndDefence'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportEducation,
                'order' => 47,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportEducation'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportHealthCare,
                'order' => 48,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportHealthCare'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportArtsAndEntertainment,
                'order' => 49,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportArtsAndEntertainment'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportOther,
                'order' => 50,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportOther'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportHouseHold,
                'order' => 51,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportHouseHold'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportExtraterritorial,
                'order' => 52,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportExtraterritorial'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportMining,
                'order' => 53,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportMining'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportManufacture,
                'order' => 54,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportManufacture'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportSupply,
                'order' => 55,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportSupply'),
            ],
            [
                'id'    => IPrtReport::IndustryIfoExportWaste,
                'order' => 56,
                'group' => trans('report.ratios.group.prt.export-industry'),
                'name'  => trans('report.PRT.fields.IndustryIfoExportWaste'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestIndustrial,
                'order' => 57,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestIndustrial'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestForestAndFishing,
                'order' => 58,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestForestAndFishing'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestBuild,
                'order' => 59,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestBuild'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestTradeAndRepair,
                'order' => 60,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestTradeAndRepair'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestLogistic,
                'order' => 61,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestLogistic'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestAccommodationAndFood,
                'order' => 62,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestAccommodationAndFood'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestInformAndCommunication,
                'order' => 63,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestInformAndCommunication'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestFinanceAndInsurance,
                'order' => 64,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestFinanceAndInsurance'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestRealEstate,
                'order' => 65,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestRealEstate'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestScience,
                'order' => 66,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestScience'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestAdministrateAndSupport,
                'order' => 67,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestAdministrateAndSupport'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestGovernmentAndDefence,
                'order' => 68,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestGovernmentAndDefence'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestEducation,
                'order' => 69,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestEducation'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestHealthCare,
                'order' => 70,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestHealthCare'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestArtsAndEntertainment,
                'order' => 71,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestArtsAndEntertainment'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestOther,
                'order' => 72,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestOther'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestHouseHold,
                'order' => 73,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestHouseHold'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestExtraterritorial,
                'order' => 74,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestExtraterritorial'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestMining,
                'order' => 75,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestMining'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestManufacture,
                'order' => 76,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestManufacture'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestSupply,
                'order' => 77,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestSupply'),
            ],
            [
                'id'    => IPrtReport::Top5IndustryInvestWaste,
                'order' => 78,
                'group' => trans('report.ratios.group.prt.invest-industry'),
                'name'  => trans('report.PRT.fields.Top5IndustryInvestWaste'),
            ],
        ];

        foreach ($ratios as $ratio) {
            $item = ReportRatio::find($ratio[ 'id' ]);
            $item->fill($ratio);
            $item->save();
        }

    }
}
